# Welcome to Jekyll!
#
# 基本信息
title: 密拉诺的博客
email: 519888682@qq.com
description: 喜欢编码，热爱动漫
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://0saber0.github.io" # the base hostname & protocol for your site, e.g. http://example.com
weibo_username: 
github_username:  0saber0

# 文章目录格式化
permalink: /:year/:month/:day/:title/
# 文章摘要分隔符
excerpt_separator: "\n\n\n\n"

# 评论组件
disqus_shortname: mi-la-nuo-de-bo-ke

# statistic analysis 统计代码
baidu_tongji_id: 
google_analytics_id: 

# 格式化文档
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-tagging-related_posts
#  - algoliasearch-jekyll

# 分页
paginate: 7

# 搜索服务
algolia:
  application_id: 'O2ZRU1NPHH'
  index_name:     '0saber0'
  search_only_api_key: 'bb92b6bc49f345ccc75dc298350925e1'

# 友情链接
links:
  -
    name: YIIU
    url: https://tomoya92.github.io/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
